### Requisição para a raiz da API
GET http://localhost:5093/

###
### =================== ENDPOINTS DE USUÁRIOS ===================
###

### Listar todos os usuários
GET http://localhost:5093/api/usuarios

### Buscar usuário por ID
GET http://localhost:5093/api/usuarios/1

### Cadastrar um novo usuário
POST http://localhost:5093/api/usuarios
Content-Type: application/json

{
    "nome": "Carlos",
    "email": "carlos@email.com"
}

### Atualizar um usuário por ID
PUT http://localhost:5093/api/usuarios/2
Content-Type: application/json

{
    "nome": "Roberto Carlos",
    "email": "roberto@email.com"
}

### Deletar um usuário por ID
DELETE http://localhost:5093/api/usuarios/2

###
### =================== ENDPOINTS DE LIVROS ===================
###

### Listar todos os livros
GET http://localhost:5093/api/livros

### Buscar livro por ID
GET http://localhost:5093/api/livros/3

### Cadastrar um novo livro
POST http://localhost:5093/api/livros
Content-Type: application/json

{
    "titulo": "O Alienista",
    "isbn": "978-8535914833",
    "anoPublicacao": 1882,
    "autorId": 1
}

### Atualizar um livro por ID
PUT http://localhost:5093/api/livros/1
Content-Type: application/json

{
    "titulo": "Dom Casmurro - Edição de Luxo",
    "isbn": "123-4567890123",
    "anoPublicacao": 1899,
    "autorId": 1
}

### Deletar um livro por ID
DELETE http://localhost:5093/api/livros/1

###
### =================== ENDPOINTS DE EMPRÉSTIMOS ===================
###

### Emprestar um livro para um usuário
# Empresta o livro de ID 3 para o usuário de ID 1
POST http://localhost:5093/api/livros/1/emprestar/1



### Devolve o livro

POST http://localhost:5093/api/livros/1/devolver


###
### =================== ENDPOINTS DE AUTOR ===================
###


### Cadastrar um novo autor 

POST http://localhost:5093/api/autores
Content-Type: application/json

{
    "nome": "Enzo bbbbbb"

}

### Cadastrar um livro usando a ID do autor

POST http://localhost:5093/api/livros
Content-Type:  application/json

{
    "titulo": "Livro 2",
    "isbn": "123-1321323",
    "anoPublicacao": 544443,
    "autorId": 4
}

### Listar todos os autores para ver o livro associado
GET   http://localhost:5093/api/autores/listar